#!/usr/bin/env bash

TITLE="LangitKetujuh Tools"
NAME=$(basename "$0")
LICENSE="GPL-3.0-or-later"
TMP="/tmp"
ANYKEY=$(echo -e 'Press any key to quit')
VERSION="1.18.42"

ARCH=$(uname -m)

usage()
{
    echo -e "\n\033[1;33m$TITLE $VERSION\033[0m"
    echo -e "\e[3mConfiguring tool for upgrade, chroot and grub installer.\e[0m"
    echo
    cat <<- EOF
license : $LICENSE
usage   : $NAME [option]
option  :
          --chroot      -c    enter chroot mode
          --downgrade   -d    downgrade & uninstall program
          --grub        -g    install grub
          --patch       -p    reinstall patch
          --remote      -r    terminal remote
          --upgrade     -u    upgrade system
          --user        -m    create new user
          --help        -h    show this help
          --version     -v    show $NAME version

EOF
}

check_root(){
    if [ $(id -u) -ne 0 ]; then
        echo -e "\033[1;91m[FAILED]\033[0m Please run as root!"
        exit
    fi
}

check_version() {
    if xbps-query -p pkgver l7-base-files | grep l7-base-files-0.142 >/dev/null 2>&1; then
        echo -e "\033[1;36m[*]\033[0m Remove temporary cache"
        rm -v /var/cache/xbps/l7-*
        echo -e "\033[1;36m[*]\033[0m Reinstall Packages version"
        # downgrade if available packages
        l7_packages=$(xbps-query -l | awk '{ print $2 }' | xargs -n1 xbps-uhelper getpkgname | grep l7 | xargs)
        xbps-install -f -y $l7_packages
    else
        echo >/dev/null 2>&1
    fi
}

check_repo() {
    # main repo
    if [ -z $(xbps-query -p state l7-repo) ]; then
        M01="l7-repo"
    else
        echo >/dev/null 2>&1
    fi
    # slow server. return to alpha.de.repo.
    # L01 l7-repo-nonfree
    if [ -n $(xbps-query -p state l7-repo-nonfree) ]; then
        echo >/dev/null 2>&1
    else
        L01="l7-repo-nonfree"
        V01="void-repo-nonfree"
    fi
    # L02 l7-repo-multilib
    if [ -n $(xbps-query -p state l7-repo-multilib) ]; then
        echo >/dev/null 2>&1
    else
        L02="l7-repo-multilib"
        V02="void-repo-multilib"
    fi
    # L03 l7-repo-multilib-nonfree
    if [ -n $(xbps-query -p state l7-repo-multilib-nonfree) ]; then
        echo >/dev/null 2>&1
    else
        L03="l7-repo-multilib-nonfree"
        V03="void-repo-multilib-nonfree"
    fi

    # check repo (remove or install)
    if [ $(echo -n "$L01 $L02 $L03" | sed 's/ //g' | wc -c) -eq 0 ]; then
        echo >/dev/null 2>&1
    else
        echo -e "\033[1;36m[*]\033[0m Change mirror repository"
        xbps-remove -y $L01 $L02 $L03
        xbps-install -Sfy $M01 $V01 $V02 $V03
        xbps-install -S
    fi
}

check_packages() {
    # P01 ardour
    if [ -n $(xbps-query -p state ardour) ]; then
        if [ -f /usr/share/ardour6/themes/dark-ardour.colors ]; then
            if [ -z "$(grep -oE "31363bff" /usr/share/ardour6/themes/dark-ardour.colors | sort -u)" ] ; then
                P01="l7-ardour"
            else
                echo >/dev/null 2>&1
            fi
        fi
    fi
    # P02 base-files
    if [ -n $(xbps-query -p state base-files) ]; then
        if [ -f /usr/bin/lsb_release ] && \
        [ -n "$(lsb_release -c | grep -E "langitketujuh")" ] ; then
            echo >/dev/null 2>&1
        else
            P02="l7-base-files"
        fi
    fi
    # P03 l7-runit-void
    if [ -n $(xbps-query -p state runit-void) ]; then
        if [ -f /etc/default/useradd ] && \
        [ -n "$(grep -oE 'NAME="LangitKetujuh OS"' /etc/os-release)" ] ; then
            echo >/dev/null 2>&1
        else
            P03="l7-runit-void"
        fi
    fi
    # P04 l7-shadow
    if [ -n $(xbps-query -p state shadow) ]; then
        if [ -f /etc/default/useradd ] && \
        [ -n "$(grep -oE 'fish' /etc/default/useradd)" ] ; then
            echo >/dev/null 2>&1
        else
            P04="l7-shadow"
        fi
    fi
    # P05 runit-backlight
    if [ -n $(xbps-query -p state runit) ]; then
        if sv status backlight | grep 'run' >/dev/null 2>&1; then
            echo >/dev/null 2>&1
        else
            P05="runit-backlight"
        fi
    fi
    # P06 goxel
    if [ -n $(xbps-query -p state goxel) ]; then
        if [ -f /usr/share/applications/goxel.desktop ] && \
        [ -n "$(grep -oE 'Name=Goxel' /usr/share/applications/goxel.desktop)" ] ; then
            echo >/dev/null 2>&1
        else
            P06="l7-goxel"
        fi
    fi
    # P06 l7-docs
    if [ -n $(xbps-query -p pkgver l7-docs | grep '202') ]; then
        echo >/dev/null 2>&1
    else
        P07="l7-docs"
    fi
    # if use kde plasma
    if [ -n $(xbps-query -p state plasma-desktopp) ]; then
        # P90 l7-plasma-desktop
        if [ -z "$(grep -E "system.upgrade" /usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/config/main.xml)" ] ; then
            P90="l7-plasma-desktop"
        else
            echo >/dev/null 2>&1
        fi
        # P91 breeze-icons
        if [ -n $(xbps-query -p state breeze-icons) ]; then
            if [ -z "$(grep -oE "#292c2f" /usr/share/icons/breeze/apps/64/distributor-logo-langitketujuh.svg)" ] ; then
                P91="l7-breeze-icons"
            else
                echo >/dev/null 2>&1
            fi
        fi
        # P92 l7-plasma-framework
        if [ -n $(xbps-query -p state plasma-framework) ]; then
            if [ -z "$(grep -E "defaultWallpaperTheme=LangitKetujuh" /usr/share/plasma/desktoptheme/default/metadata.desktop)" ] ; then
                P92="l7-plasma-framework"
            else
                echo >/dev/null 2>&1
            fi
        fi
        # P93 l7-sddm
        if [ -n $(xbps-query -p state sddm) ]; then
            if [ -z "$(grep -E 'langitketujuh' /etc/sddm.conf.d/kde_settings.conf)" ] ; then
                P93="l7-sddm"
            else
                echo >/dev/null 2>&1
            fi
        fi
        # P94 l7-kservice
        if [ -n $(xbps-query -p state kservice) ]; then
            if [ -z "$(grep -oE 'LangitKetujuh' /etc/xdg/menus/applications.menu)" ] ; then
                P94="l7-kservice"
            else
                echo >/dev/null 2>&1
            fi
        fi
    else
        echo >/dev/null 2>&1
    fi
    # check packages
    if [ $(echo -n "$P01 $P02 $P03 $P04 $P05 $P06 $P07 $P90 $P91 $P92 $P93 $P94" | sed 's/ //g' | wc -c) -eq 0 ]; then
        echo >/dev/null 2>&1
    else
        echo -e "\033[1;36m[*]\033[0m Reinstall patch"
        xbps-install -fIy $P01 $P02 $P03 $P04 $P05 $P06 $P07 $P90 $P91 $P92 $P93 $P94
    fi
    # check service
    for s in adb backlight bluetoothd bluez-alsa colord earlyoom ntpd zramen _pipewire; do
        if sv status ${s} | grep run >/dev/null 2>&1; then
            echo >/dev/null 2>&1
        else
            ln -s -f /etc/sv/${s} /var/service/
        fi
    done
}

check_qtwebengine_dark_mode() {
    # if comment
    if [ -f /etc/environment ] && grep -E "force-dark-mode" /etc/environment | grep '#' >/dev/null 2>&1; then
        echo -e "\033[1;36m[*]\033[0m Enable Qtwebengine dark mode"
        sed -i 's/#QTWEBENGINE_CHROMIUM_FLAGS=--force-dark-mode/QTWEBENGINE_CHROMIUM_FLAGS=--force-dark-mode/' /etc/environment >/dev/null 2>&1
    else
        # if available, then skip
        if grep -E "force-dark-mode" /etc/environment >/dev/null 2>&1; then
            echo >/dev/null 2>&1
        else
            echo -e "\033[1;36m[*]\033[0m Enable Qtwebengine dark mode"
            echo "QTWEBENGINE_CHROMIUM_FLAGS=--force-dark-mode" >> /etc/environment
        fi
    fi
}

check_enable_rtc_windows() {
    if [ -d /boot/efi/EFI/Microsoft ]; then
        if [ -f /etc/rc.conf ] && grep -E '#HARDWARECLOCK="UTC"' /etc/rc.conf; then
            echo -e "\033[1;36m[*]\033[0m Enable localtime for Windows dualboot"
            sed -i 's/#HARDWARECLOCK="UTC"/HARDWARECLOCK="localtime"/' /etc/rc.conf
            echo -e "[*] HARDWARECLOCK=localtime"
            for s in ntpd openntpd ; do
                if [ -h /var/service/${s} ]; then
                    rm -v /var/service/${s} >/dev/null 2>&1
                    echo -e "[*] removed '/var/service/${s}'"
                fi
            done
        fi
    else
        echo >/dev/null 2>&1
    fi
}

check_welcome_runit() {
    if [ -f /etc/runit/1 ] && grep -E "LangitKetujuh" /etc/runit/1 >/dev/null 2>&1; then
        echo >/dev/null 2>&1
    else
        echo -e "\033[1;36m[*]\033[0m Enable welcome to LangitKetujuh"
        sed -i 's/Void/LangitKetujuh/g' /etc/runit/1

    fi
}

check_welcome_grub() {
    if [ -f /etc/default/grub ] && grep -E "LangitKetujuh" /etc/default/grub >/dev/null 2>&1; then
        echo >/dev/null 2>&1
    else
        echo -e "\033[1;36m[*]\033[0m Enable LangitKetujuh grub name"
        sed -i /etc/default/grub -res'#^(GRUB_DISTRIBUTOR).*#GRUB_DISTRIBUTOR="LangitKetujuh"#'
        update-grub
    fi
}

prober_update_grub() {
    os-prober
    update-grub
}

check_enable_os_prober() {
    if [ -d /boot/efi/EFI ]; then # if uefi singleboot
        if [ $(ls /boot/efi/EFI/ | wc -l) -eq 1 ]; then
            if [ -f /etc/default/grub ] && grep -E "GRUB_DISABLE_OS_PROBER=false" /etc/default/grub >/dev/null 2>&1; then
                sed -i -e "/GRUB_DISABLE_OS_PROBER=false/d" /etc/default/grub
            else
                echo >/dev/null 2>&1
            fi
        else # if uefi dualboot or more
            if [ -f /etc/default/grub ] && grep -E "GRUB_DISABLE_OS_PROBER=false" /etc/default/grub | grep '#' >/dev/null 2>&1; then
                echo -e "\033[1;36m[*]\033[0m Enable GRUB os-prober"
                echo -e "\033[1;36m[*] Detect Other EFI:\033[0m" $(ls /boot/efi/EFI/ | xargs)
                sed -i -e "/GRUB_DISABLE_OS_PROBER=false/d" /etc/default/grub
                echo "GRUB_DISABLE_OS_PROBER=false" >> /etc/default/grub
                prober_update_grub
            else
                if grep -E "GRUB_DISABLE_OS_PROBER=false" /etc/default/grub >/dev/null 2>&1; then
                    echo >/dev/null 2>&1
                else
                    echo -e "\033[1;36m[*]\033[0m Enable GRUB os-prober"
                    echo -e "\033[1;36m[*] Detect Other EFI:\033[0m" $(ls /boot/efi/EFI/ | xargs)
                    echo "GRUB_DISABLE_OS_PROBER=false" >> /etc/default/grub
                    prober_update_grub
                fi
            fi
        fi
    else # for legacy singleboot or more
        if [ -f /etc/default/grub ] && grep -E "GRUB_DISABLE_OS_PROBER=false" /etc/default/grub >/dev/null 2>&1; then
            echo >/dev/null 2>&1
        else
            echo -e "\033[1;36m[*]\033[0m Enable GRUB os-prober"
            echo "GRUB_DISABLE_OS_PROBER=false" >> /etc/default/grub
            prober_update_grub
        fi
    fi
}

check_all() {
    check_version
    check_repo
    check_packages
    check_qtwebengine_dark_mode
    check_enable_rtc_windows
    check_welcome_runit
    check_welcome_grub
    check_enable_os_prober
}

quit() {
    echo
    read -n 1 -s -r -p "$ANYKEY"
    exit 0
}

for arg in "$@"; do
    case $arg in
        --upgrade|-u)
            check_root
            echo -e "\033[1;36mLangitKetujuh Upgrade System\033[0m"
            echo -e "\e[3mUpgrade applications and operating systems from repositories\e[0m"
            echo
            echo -e "\033[1;36m[1]\033[0m Synchronization"
            xbps-install -S;
            echo -e "\033[1;36m[2]\033[0m Full system upgrade"
            xbps-install -uI
            echo -e "\033[1;36m[3]\033[0m Check trouble and patch"
            check_all
            echo -e "\033[1;36m[4]\033[0m \033[1;33m(Optional)\033[0m Remove all old kernels?"
            read -e -p "[*] Do you want to continue? [y/N]: " KERNEL
            if [[ $KERNEL =~ ^[Yy]$ ]]; then
                echo -e "[*] Yes, wait a minutes"
                vkpurge rm all
            fi
            echo -e "\033[1;36m[5]\033[0m \033[1;33m(Optional)\033[0m Remove obsolete and orphans packages?"
            read -e -p "[*] Do you want to continue? [y/N]: " CACHE
            if [[ $CACHE =~ ^[Yy]$ ]]; then
                echo -e "[*] Yes, wait a minutes"
                xbps-remove -vOoy
            fi
            quit
        ;;
        --remote|-r)
            echo -e "\033[1;36mLangitKetujuh Terminal Remote\033[0m"
            echo -e "\e[3mRemotely to other devices using upterm\e[0m"
            echo
            if find ~/.ssh/ -name "*.pub" -type f >/dev/null 2>&1; then
                echo -e >/dev/null 2>&1
            else
                echo -e "[*] Create new ssh key"
                ssh-keygen -o -a 100 -t ed25519 -f ~/.ssh/id_ed25519 >/dev/null 2>&1;
                echo
            fi
            echo -e "[*] Remote connecting"
            upterm host
            echo -e "[*] Remote exit!"
        ;;
        --chroot|-c)
            check_root
            echo -e "\033[1;36mLangitKetujuh Chroot Tools\033[0m"
            echo -e "\e[3mChange root and fix them\e[0m"
            echo
            lsblk -o name,fstype,fsavail,fsused,fsuse%,size,mountpoint
            echo
            read -e -p "[*] Root partition (ex: sda2): " root_part
            mount /dev/$root_part /mnt/
            read -e -p "[*] Boot mode uefi (y/n): " boot_opt
            if [[ $boot_opt =~ ^[Yy]$ ]]; then
                # for separate efi partition (uefi)
                read -e -p "[*] Boot efi partition (ex: sda1): " boot_part
                boot_target="boot/efi"
                mkdir -p /mnt/$boot_target
                mount /dev/$boot_part /mnt/$boot_target
            else
                # for separate bios partition (legacy)
                read -e -p "[*] Separate boot bios partition (y/n): " boot_separate
                if [[ $boot_separate =~ ^[Yy]$ ]]; then
                    read -e -p "[*] Boot bios partition (ex: sda1): " boot_part
                    boot_target="boot"
                    mkdir -p /mnt/$boot_target
                    mount /dev/$boot_part /mnt/$boot_target
                else
                    # for merged root & bios partition (legacy)
                    echo >/dev/null 2>&1
                fi
            fi
            # mount sys, dev, proc, run
            for dir in dev proc sys run;
            do mkdir -p /mnt/$dir ;
                mount --rbind /$dir /mnt/$dir ;
                mount --make-rslave /mnt/$dir ;
            done
            # enable network
            cp /etc/resolv.conf /mnt/etc/
            # chroot mode
            echo
            chroot /mnt/ /bin/fish
            umount -R /mnt >/dev/null 2>&1
            echo -e "[*] Chroot exit"
        ;;
        --grub|-g)
            check_root
            echo -e "\033[1;36mLangitKetujuh Grub Installer\033[0m"
            echo -e "\e[3mInstalling grub & bootloader\e[0m"
            echo
            lsblk -o name,fstype,fsavail,fsused,fsuse%,size,mountpoint
            echo
            read -e -p "[*] Boot mode UEFI (y/n): " boot_opt
            if [[ $boot_opt =~ ^[Yy]$ ]]; then
                read -e -p "[*] Continue install grub (Y/n): " continue
                if [[ $continue =~ ^[Yy]$ ]]; then
                    echo
                    grub-install --target=x86_64-efi \
                    --efi-directory=/boot/efi --bootloader-id="LangitKetujuh"
                    check_enable_os_prober
                else
                    exit
                fi
            else
                read -e -p "[*] Bootloader (ex: sda): " boot_loader
                read -e -p "[*] Continue install grub (Y/n): " continue
                if [[ $continue =~ ^[Yy]$ ]]; then
                    echo
                    grub-install /dev/$boot_loader
                    check_enable_os_prober
                else
                    exit
                fi
            fi
        ;;
        --user|-m)
            check_root
            echo -e "\033[1;36mLangitKetujuh User Creator\033[0m"
            echo -e "\e[3mCreating new userr\e[0m"
            echo
            read -e -p "[*] User name: " user_name
            read -e -p "[*] Full name: " full_name
            read -e -p "[*] As Administrator (Y/n): " admin_user
            if [[ $admin_user =~ ^[Yy]$ ]]; then
                user_group="$user_name,wheel"
            else
                user_group="$user_name"
            fi
            echo -e "[*] Create user: \033[1;36m$user_name ($full_name)\033[0m"
            read -e -p "[*] Continue create user (Y/n): " continue
            if [[ $continue =~ ^[Yy]$ ]]; then
                useradd $user_name -c "$full_name"
                echo -e "[*] Create new user password"
                passwd $user_name
                usermod -a $user_name -G $user_group,audio,bluetooth,colord,video,cdrom,floppy,kvm,optical,xbuilder
                echo -e "[*] User $user_name created successfully"
            else
                exit
            fi
        ;;
        --patch|-p)
            check_all
        ;;
        --downgrade|-d)
            check_root
            echo -e "\033[1;36m[1] Display Callibrator\033[0m"
            xbps-remove -R dispcalGUI
            echo -e "\033[1;36m[2] Add-ons 2D Software\033[0m"
            xbps-remove -R gmic gmic-gimp gimp-lqr-plugin xsane-gimp resynthesizer l7-krita
            echo -e "\033[1;36m[3] Photography Software\033[0m"
            xbps-remove -R digikam rawtherapee hugin Converseen
            echo -e "\033[1;36m[4] Non-linear Editor\033[0m"
            xbps-remove -R kdenlive handbrake mkvtoolnix-gui
            echo -e "\033[1;36m[5] Font Maker\033[0m"
            xbps-remove -R fontforge
            echo -e "\033[1;36m[6] Digital Painting\033[0m"
            xbps-remove -R krita l7-krita gmic-krita
            echo -e "\033[1;36m[7] Recorder & Broadcaster Software\033[0m"
            xbps-remove -R obs l7-obs
            echo -e "\033[1;36m[8] Layout & Desktop Publishing\033[0m"
            xbps-remove -R scribus l7-scribus
            echo -e "\033[1;36m[9] 2D/3D Animation Full Feature\033[0m"
            xbps-remove -R blender l7-blender synfigstudio opentoonz
            echo -e "\033[1;36m[10] Audio Production\033[0m"
            xbps-remove -R audacity l7-audacity ardour l7-ardour kid3 \
            soundkonverter lmms freepats cmt alsa-plugins-jack zita-ajbridge \
            zita-alsa-pcmi zita-at1 zita-njbridge zita-resampler \
            alsa-plugins-samplerate calf fftw rubberband librubberband \
            ladspa-bs2b speex mda-lv2 soundfont-fluid
            echo -e "\033[1;36m[11] Extra Google Fonts\033[0m"
            xbps-remove -R google-fonts-ttf
            echo -e "\033[1;36m[12] Game Engine Creator Mutiplatform\033[0m"
            xbps-remove -R godot l7-godot
            echo -e "\033[1;36m[13] CAD Sofware\033[0m"
            xbps-remove -R freecad LibreCAD
            echo -e "\033[1;36m[14] Program Compiler\033[0m"
            xbps-remove -R automake bison fakeroot flex gdb libtool m4 patch \
            pkg-config qemu-user-static scons yasm gcc-objc++ llvm clang icu cmake
        ;;
        --help|-h)
            usage
            exit 0
        ;;
        --version|-v)
            echo -e "\033[1;33m $NAME\033[0m version $VERSION"
            exit 0
        ;;
        *)
            usage
            exit 0
    esac
done
